import Vuex from "vuex"
import Vue from "vue"

Vue.use(Vuex)

export default new Vuex.Store({
    name: "store",
    state: {
        loggedIn: false,
        count: 0,
        seven: [1, 3, 4, 6, 7, 9, 0],
        movies: [
            {
                id: 1,
                title: "Crazy primitive 2",
                director: "Joel Crawford",
                actor: "Nicholas Cage,Emma stone,Ryan Reynolds",
                blurb: "After fleeing the cave and surviving the doomsday crisis the Gulu family decided to find a new home.In the middle of the journey guy has become a member of Gulu's family but what bothers GUARO is that guy and his daughter Emma stone talk to each other every day and they also want to form a small family of two.Just as Gulu's family were hungry they found a fertile land with rich food hidden in a high wall. The civilized couple who originally opened up this paradise hope and Phil were friends of Gai's parents who had died.After the initial hospitality hope and Phil who are determined to make up for Gai and his daughter Xiaoxiao find that the Gulu family has become a stumbling block. In order to get Gai over they use a mental attack.The two families are fighting each other. Gai and Xiaoyi have a rift but they don't know the danger is approaching",
                classification: [
                    "comic",
                    "animation",
                    "adventure"
                ],
                rank: 7.9,
                release_time: "2020-11-27 (Chinese mainland",
                running_time: 95,
                is_released: 1,
                pic_src: "/poster/p2624607255.jpg",
                cert: "U",
                sell_weeks: [13.6, 16.1, 15.0],
                totalTaking: 313,
                avgDayTaking: 14.9,
            },
            {
                id: 2,
                title: "Escape from doomsday",
                director: "Rick Roman Wolf",
                actor: "Gerald Butler,David danman",
                blurb: "Scientists have found that two comets in the universe are rapidly approaching the earth. If there is no accident they will eventually hit the earth and bring incalculable losses to the earth.In order to avoid causing world-class panic the government blocked the news and secretly built a very strong fortress in Greenland. Only those who hide in the fortress can get a chance of survival and the conditions for entering the fortress are very harsh.Jeff (Gerard Butler) is an architectural engineer. He gets the opportunity to enter the fort so he decides to take his wife Alison (Morena BACCARIN) and son Nathan (Roger Dale Floyd) to Greenland.But in the middle of the journey the military aware of the truth of the incident started a riot.",
                classification: [
                    "plot",
                    "science_fiction",
                    "disaster"
                ],
                rank: 5.5,
                release_time: "2020-11-20 (Chinese mainland",
                running_time: 119,
                is_released: 1,
                pic_src: "/poster/p2626067725.jpg",
                cert: "12",
                sell_weeks: [17.1, 14.6, 16.7, 15.0],
                totalTaking: 444,
                avgDayTaking: 15.9,
            },
            {
                id: 3,
                title: "Soul searching",
                director: "Cheng Weihao",
                actor: "Zhang Zhen,Zhang Junning,sun Anke",
                blurb: "Wang Shicong chairman of the famous group died at home. The prosecutor in charge of the case Liang Wenchao (Zhang Zhen) and his wife a Pao (Zhang Junning) learned in the investigation that the son of the deceased Wang Tianyou (Lin Hui Min) his young newlywed wife Li Yan (Sun Anke) his longtime partner Wan Yufan (Li Mingshun) and even his ex-wife Tang Suzhen (Zhang Baijia) diedThere are intricate connections between everyone.Ah Pao discovered the amazing secret hidden behind the caseThe film is adapted from Jiang Bo's novel the art of moving souls.",
                classification: "Science_fiction crime suspense",
                rank: 7,
                release_time: "2021-01-15 (Chinese mainland",
                running_time: 130,
                is_released: 1,
                pic_src: "/poster/p2629413230.jpg",
                cert: "12",
                sell_weeks: [14.7, 16.3, 15.3],
                totalTaking: 324,
                avgDayTaking: 15.4,
            },
            {
                id: 4,
                title: "Love like a flower",
                director: "Nobuhiro Doi ",
                actor: "Jiantian Jianghui",
                blurb: "The film is the first big screen collaboration of Yutai Tui director of Quartet and Yuji Sakamoto screenwriter.The story tells that the hero and heroine meet by chance because they miss the last tram at Mingda front station in Tokyo. Then they start a five-year love in which the times time place and all the accidents are synchronous like fate. It shows how they are confused when they are neither adults nor children.",
                classification: "Plot love",
                rank: 8.5,
                release_time: "2021-01-29 (Japan) ",
                running_time: 124,
                is_released: 1,
                pic_src: "/poster/p2623936924.jpg",
                cert: "PG",
                sell_weeks: [17.1, 14.1, 16.3, 14.9, 14.1],
                totalTaking: 536,
                avgDayTaking: 15.3,
            },
            {
                id: 5,
                title: "See Nara again",
                director: "soaring flight",
                actor: "Wu Yanshu,Yingze",
                blurb: "The film tells a story of a mother daughter relationship that spans 60 years.Nearly 80 years old grandmother Chen Huiming (Wu Yanshu) alone to Nara looking for lost daughter Chen Lihua.With the help of the second generation of orphan Ozawa (Yingze) and retired policeman Yixiong (Guocun Falcon) we find many people who have contacted and helped Lihua.In this process Chen Huiming experienced Lihua's life after her arrival in Japan and her relationship with Ozawa and Ichio became closer during this journey.",
                classification: [
                    "plot"
                ],
                rank: 7.7,
                release_time: "2021-03-19 (Chinese mainland",
                running_time: 100,
                is_released: 1,
                pic_src: "/poster/p2634228191.jpg",
                cert: "U",
                sell_weeks: [16.9, 14.9, 12.9],
                totalTaking: 312,
                avgDayTaking: 14.9,
            },
            {
                id: 6,
                title: "eliminate the rascals",
                director: "Liu Haoliang",
                actor: "Wang Qianyuan,spring and summer",
                blurb: "\"In the 1990s criminal police Zhong Cheng was ordered to hunt down the hawk Gang a bandit group.This group of bandits committed a series of robberies. They were well-trained and well disciplined. Zhang falcon the leader of the group made repeated malicious provocations aiming at Zhong Cheng.In order to bring the \"\"Eagle Gang\"\" to justice Zhong Cheng led the criminal police team to death and vowed to fight against the evil forces to the end.Over the past few years the police and bandits staged a fierce battle. The fierce bandits became more and more rampant. The police approached step by step and the two sides fought each other to the death\"",
                classification: [
                    "plot",
                    "crime",
                    "action"
                ],
                rank: 6.3,
                release_time: "2020-11-20 (Chinese mainland",
                running_time: 95,
                is_released: 1,
                pic_src: "/poster/p2625777429.jpg",
                cert: "12",
                sell_weeks: [17.1, 13.9, 16.1, 16.7],
                totalTaking: 447,
                avgDayTaking: 16.0,
            },
            {
                id: 7,
                title: "One second",
                director: "Zhang Yimou",
                actor: "Zhang Yi,Liu haocun,Fan Wei",
                blurb: "The film tells the story of Zhang Jiusheng and Liu guinv who failed to catch up with the number of films and formed an indissoluble bond because of a film.The story is inspired by Zhang Yimou's early experience which is his style of recalling culture and seeking roots.",
                classification: [
                    "plot"
                ],
                rank: 7.8,
                release_time: "2020-11-27 (Chinese mainland",
                running_time: 104,
                is_released: 1,
                pic_src: "/poster/p2628373757.jpg",
                cert: "12",
                sell_weeks: [16.6, 13.6, 14.1],
                totalTaking: 310,
                avgDayTaking: 14.8,
            },
            {
                id: 8,
                title: "escape",
                director: "Anish chaganti",
                actor: "Sarah Paulson,Kira Allen,pat Healy",
                blurb: "\"Annish chaganti director of \"\"Internet Enigma\"\" tells the story of Sarah Paulson's mother raising her daughter alone (Keira Allen). When her daughter learns the secret of her mother's sin her life begins to collapse.\"",
                classification: [
                    "suspense",
                    "horror"
                ],
                rank: 6.7,
                release_time: "2020-11-20 (US network) ",
                running_time: 90,
                is_released: 1,
                pic_src: "/poster/p2587085523.jpg",
                cert: "15",
                sell_weeks: [15.1, 17.1, 16.4, 15.3],
                totalTaking: 448,
                avgDayTaking: 16.0,
            },
            {
                id: 9,
                title: "Qingyaji",
                director: "Guo Jingming",
                actor: "Zhao Youting,Dunlun,Wang Ziwen",
                blurb: "Strange phenomena frequently appear in Tiandu city. Mages come from all sides to try to find out the truth.In the process of searching for the truth Yin Yang master Qingming (Zhao Youting) meets the warrior Boya (Deng Lun) mage LONGYE (Chunxia) and he Shouyue (Wang Duo). They decide to join hands to investigate.Deep palace the princess (Prince ornament) with a huge secret deep in this mystery... But did not expect this hidden behind a sad past.A crisis is coming quietly. At the critical moment some people are confidants some people are sweethearts and some people are peaceful in the world. In order to protect what they love in their hearts we fight to death",
                classification: [
                    "love",
                    "fantasy"
                ],
                rank: 5.1,
                release_time: "2020-12-25 (Chinese mainland",
                running_time: 132,
                is_released: 1,
                pic_src: "/poster/p2622484010.jpg",
                cert: "PG",
                sell_weeks: [14.4, 13.1, 13.0, 15.1, 15.0],
                totalTaking: 495,
                avgDayTaking: 14.1,
            },
            {
                id: 10,
                title: "Jin Gangchuan",
                director: "Guan Hu Guo fan Lu Yang",
                actor: "Zhang Yi,Wu Jing,Li jiuxiao",
                blurb: "In 1953 the war to resist US aggression and aid Korea entered the final stage and the volunteers launched the last large-scale campaign in Jincheng.In order to arrive at the designated time and put more combat power into the front line of Jincheng the volunteers constantly resisted the fierce bombardment of enemy planes in the case of material shortage and armed disparity and used their flesh and blood to repair the wooden bridges in the war time after time.A little-known history unfolds slowly in the undercurrent of vajrakawa",
                classification: [
                    "plot",
                    "war"
                ],
                rank: 6.5,
                release_time: "2020-10-23 (Chinese mainland",
                running_time: 122,
                is_released: 1,
                pic_src: "/poster/p2623301908.jpg",
                cert: "12A",
                sell_weeks: [14.7, 13.7, 13.0, 13.9],
                totalTaking: 387,
                avgDayTaking: 13.8,
            },
            {
                id: 11,
                title: "creed",
                director: "Christopher Nolan",
                actor: " Robert Pattinson,Elizabeth debitsky",
                blurb: "\"The survival of the world is at stake. \"\"Creed\"\" is the only clue and weapon.The protagonist shuttles around the world carrying out secret service activities trying to reveal the mystery of \"\"creed\"\" and completing a mysterious task beyond the real time.This task is not a journey of time but a reversal of time and space.\"",
                classification: "Plot action science_fiction",
                rank: 7.7,
                release_time: "2020-09-04 (Chinese mainland",
                running_time: 150,
                is_released: 1,
                pic_src: "/poster/p2618403186.jpg",
                cert: "12A",
                sell_weeks: [15.1, 15.9, 16.3, 16.4],
                totalTaking: 446,
                avgDayTaking: 15.9,
            },
            {
                id: 12,
                title: "Cheat the world JP: Princess",
                director: "Tanaka Liang",
                actor: "Yasumi Nagasawa,xiaori Wenshi",
                blurb: "The stage of the story is set in Singapore. The target of the fraud trio which is composed of Nagasawa Yamei Dongchu Changda and xiaori XiangWenShi is the 10 trillion yen legacy left by the world-famous tycoon Hu Leimeng.",
                classification: [
                    "plot",
                    "comedy"
                ],
                rank: 7.3,
                release_time: "2020-07-23 (Japan) ",
                running_time: 124,
                is_released: 1,
                pic_src: "/poster/p2610002857.jpg",
                cert: "PG",
                sell_weeks: [13.7, 15.0, 16.0, 15.7, 12.9],
                totalTaking: 513,
                avgDayTaking: 14.7,
            },
            {
                id: 13,
                title: "Doraemon: Daxiong's new dinosaur",
                director: "It's dawn today",
                actor: " Huimei Ohara,jiashuyoumei",
                blurb: "With the help of Doraemon's time burden Daxiong successfully hatched two new dinosaurs with wings that had never been found before.Daxiong and his friends decided to take the little dinosaurs back to their own time. A thrilling Cretaceous adventure is about to be staged.This is the 50th anniversary of Doraemon comic series and the 40th work of Doraemon series.Brand new story brand new hero brand new adventure brand new start!",
                classification: [
                    "animation",
                    "adventure",
                    "fantasy"
                ],
                rank: 7.4,
                release_time: "2020-12-11 (Chinese mainland",
                running_time: 110,
                is_released: 1,
                pic_src: "/poster/p2624375776.jpg",
                cert: "U",
                sell_weeks: [14.7, 16.0, 13.9, 16.4],
                totalTaking: 427,
                avgDayTaking: 15.2,
            },
            {
                id: 14,
                title: "The queen of Blues",
                director: "George Woolf",
                actor: "Viola Davis,Chadwick Bosman,Coleman Domingo",
                blurb: "\"In the 1920s in an afternoon recording in Chicago the band members are waiting for the pioneering performer the legendary \"\"mother of blues\"\" Ma Renny (Oscar winner Viola Davis) during which the atmosphere becomes increasingly tense.At the end of the recording fearless and hot tempered Ma and her white agent and producer had a will fight over her music control.Ambitious trumpeter Levi (Chadwick Bosman) appreciates Ma's girlfriend very much and is determined to have a place in the music industry. When the band is waiting in the secluded rehearsal room of the studio he urges the musicians to reveal the truth which will change their lives forever.Adapted from a play by two time Pulitzer Prize winner Auguste Wilson \"\"the queen of blues\"\" extols the transformative power of blues and artists who refuse to let social prejudice control their values.Directed by George Woolf the film is adapted by Reuben Santiago Hudson and produced by Denzel Washington and Todd black who have won Oscar nominations for \"\"the fence.\"\".Coleman Domingo green Truman Michael Potts Taylor Peggy and Dushan Brown co starred and Emmy winner Branford massalis played the score.\"",
                classification: [
                    "plot",
                    "music"
                ],
                rank: 6.6,
                release_time: "2020-12-18 (US network) ",
                running_time: 94,
                is_released: 1,
                pic_src: "/poster/p2623338779.jpg",
                cert: "U",
                sell_weeks: [15.3, 13.9, 14.4, 17.0],
                totalTaking: 424,
                avgDayTaking: 15.1,
            },
            {
                id: 15,
                title: "World News",
                director: "Paul Greengrass",
                actor: "Tom Hanks,Helena zegel,Elizabeth Marvel",
                blurb: "Five years after the end of the civil war in the United States the retired officer of the three wars Captain Jefferson kelkidd (Tom Hanks) now travels from small town to small town as a newspaper reader sharing wonderful news from all over the world with local residents.In the plains of Texas he meets Johanna (Helena zegel) a 10-year-old girl who was abducted and adopted by the kaiowa Indians six years ago.Johanna was hostile to a world she had never experienced and was forced to return to her aunt and uncle.Captain Kidd promised to escort the girl back to where she belonged by law.They have to wade hundreds of miles in the harsh wilderness and the two will face enormous challenges from both human and nature in their search for a place they can both call home.",
                classification: [
                    "action"
                ],
                rank: 7.1,
                release_time: "2020-12-25 (USA) ",
                running_time: 118,
                is_released: 1,
                pic_src: "/poster/p2623549939.jpg",
                cert: "PG",
                sell_weeks: [13.6, 14.6, 13.7, 16.0, 13.0],
                totalTaking: 496,
                avgDayTaking: 14.2,
            },
            {
                id: 16,
                title: "HMS Greyhound ",
                director: "Alan Schneider",
                actor: "Tom Hanks,Stephen Graham,Elizabeth Sue",
                blurb: "At the beginning of World War II the convoy composed of 37 allied warships under the command of an American destroyer led by Captain Ernest Krauss (Tom Hanks) crosses the dangerous North Atlantic Ocean and at the same time interacts with the wolf pack of German U-type submarines.",
                classification: [
                    "plot",
                    "war"
                ],
                rank: 8,
                release_time: "2020-07-10 (USA) ",
                running_time: 91,
                is_released: 1,
                pic_src: "/poster/p2591289975.jpg",
                cert: "PG",
                sell_weeks: [17.0, 16.3, 13.6, 14.6, 14.4],
                totalTaking: 531,
                avgDayTaking: 15.2,
            },
            {
                id: 17,
                title: "Supernova",
                director: "Harry McQueen",
                actor: "Colin Firth,Stanley Tuzi,Pippa Heywood",
                blurb: "Sam and tusk (faith and tooch) are a couple who have been together for 20 years. They plan to drive across England to visit friends family and places they used to stay.Since tusk was diagnosed with Alzheimer's two years ago their time together has become the most important thing between them.But as the journey went on their ideas about the future were full of conflict and the secrets of the past were constantly emerging and their love for each other had never been tested as much as it is now.Finally they have to face the question of what it means to love each other in the face of Tusk's disease.",
                classification: [
                    "love",
                    "sex"
                ],
                rank: 7.3,
                release_time: "2020-09-24 (St. Sebastian Film Festival) ",
                running_time: 93,
                is_released: 1,
                pic_src: "/poster/p2629862197.jpg",
                cert: "U",
                sell_weeks: [14.9, 15.9, 13.0, 16.1, 13.1],
                totalTaking: 511,
                avgDayTaking: 14.6,
            },
            {
                id: 18,
                title: "Wrong turn",
                director: "Michael P. Nelson",
                actor: "Charlotte Vega,Emma Dumont,Matthew modien",
                blurb: "A group of close friends decided to go hiking in West Virginia only to encounter a tribe that is not friendly to strangers a tribe that has lived in the mountains for hundreds of years.Facing the death of her good friends the heroine uses her courage and wisdom to protect herself and finally gets out of danger.",
                classification: [
                    "horror"
                ],
                rank: 5.8,
                release_time: "2021-01-26 (USA) ",
                running_time: 110,
                is_released: 1,
                pic_src: "/poster/p2628525496.jpg",
                cert: "15",
                sell_weeks: [15.9, 13.0, 12.9, 16.0],
                totalTaking: 404,
                avgDayTaking: 14.4,
            },
            {
                id: 19,
                title: "good luck and happiness to you",
                director: "Mirs",
                actor: "Wang Jixiang,Dapeng,Liu Lu",
                blurb: "Dapeng directed a realistic literary film for the first time. The story tells of a comedy director who came back to his hometown in the Northeast countryside with a whim hoping to make a literary film about how his family spent the new year. As a result he encountered a series of accidents.The family members gathered for the film finished the final gathering.",
                classification: [
                    "plot",
                    "family"
                ],
                rank: 7.9,
                release_time: "2021-01-29 (Chinese mainland",
                running_time: 80,
                is_released: 1,
                pic_src: "/poster/p2632185061.jpg",
                cert: "U",
                sell_weeks: [13.0, 15.3, 15.0, 13.3, 14.1],
                totalTaking: 495,
                avgDayTaking: 14.1,
            },
            {
                id: 20,
                title: "Wolf Walker",
                director: "Tom Morris Stewart",
                actor: "Sean bin,Horner neffey,EVA Whitacre",
                blurb: "It tells the magical experience of 11 year old girl rofin.As a young apprentice hunter rofin came to Ireland with her father to kill the last wolves there but the change came. She found the wolf walker and then a series of strange stories happened",
                classification: [
                    "animation",
                    "adventure",
                    "fantasy"
                ],
                rank: 8,
                release_time: "2020-09-12 (Toronto Film Festival) ",
                running_time: 103,
                is_released: 1,
                pic_src: "/poster/p2622396801.jpg",
                cert: "PG",
                sell_weeks: [17.0, 16.4, 14.0, 15.1],
                totalTaking: 438,
                avgDayTaking: 15.6,
            },
            {
                id: 21,
                title: "traces",
                director: "John Lee Hancock ",
                actor: "Denzel Washington,Lamy Marek,Jared Leto",
                blurb: "Kern County patrol Joe Dicken nicknamed dick (Denzel Washington) is sent to Los Angeles for what should have been a simple and straightforward task of collecting evidence.Instead he was involved in a hunt for the serial killers who are wreaking havoc in the city.Leading the arrest is Los Angeles County Sheriff Jim Beckett (Lamy Marek) who is surprised by Dick's police intuition so he secretly seeks his help.But when they track down the main suspect Abbott SPAMA (played by Jared Leto) beckster doesn't realize that the investigation has aroused Dick's unpleasant memories of the past and the dark secrets unearthed may be more involved than threatening the investigation.",
                classification: [
                    "plot",
                    "crime",
                    "thriller"
                ],
                rank: 6.5,
                release_time: "2021-01-29 (USA) ",
                running_time: 127,
                is_released: 1,
                pic_src: "/poster/p2628906317.jpg",
                cert: "PG",
                sell_weeks: [13.1, 13.6, 14.4],
                totalTaking: 288,
                avgDayTaking: 13.7,
            },
            {
                id: 22,
                title: "witch",
                director: "Robert zemigis",
                actor: "Anne Hathaway,Octavia Spencer,Stanley Tuzi",
                blurb: "Based on the children's novel of the same name written by rold Dahl (the original author of Charlie and the Chocolate Factory) the film is set partly in Norway and partly in England. It tells the story of a 7-year-old boy who lives with his grandmother. There are evil witches in the world. Once he meets a Witch and is turned into a mouse he must try his best to prevent them from destroying the world.",
                classification: [
                    "adventure",
                    "comedy",
                    "fantasy"
                ],
                rank: 5.8,
                release_time: "2020-10-22 (USA) ",
                running_time: 106,
                is_released: 1,
                pic_src: "/poster/p2621884130.jpg",
                cert: "PG",
                sell_weeks: [13.0, 16.3, 13.6, 13.7],
                totalTaking: 396,
                avgDayTaking: 14.1,
            },
            {
                id: 23,
                title: "/polat 2",
                director: "Jason weineller",
                actor: "Sasha Byron Cohen,Maria baclova,Mike burns",
                blurb: "It tells the story of Polat's return to the United States from Kazakhstan.",
                classification: [
                    "comedy"
                ],
                rank: 7.2,
                release_time: "2020-10-23 (US network) ",
                running_time: 95,
                is_released: 1,
                pic_src: "/poster/p2621751023.jpg",
                cert: "15",
                sell_weeks: [16.6, 12.9, 17.0, 16.6, 13.1],
                totalTaking: 533,
                avgDayTaking: 15.2,
            },
            {
                id: 24,
                title: "Emergency rescue",
                director: "Lin Chaoxian",
                actor: "Peng Yuyan,Wang Yanlin,Xin Zhilei",
                blurb: "\"The capsized and sunken drilling platform the head of the oil tanker and the full passenger plane falling into the sea.Gao Qian (Peng Yuyan) captain of the maritime emergency response special team Fang Yuling (Xin Zhilei) and Zhao Cheng (Wang Yanlin) lead the team to arrive at the first time. They stand in the front of the roar of water and fire and at the back of the emergency evacuation. They fight against natural and man-made disasters with their lives.But in the face of nature the secret service has no super power after all. Their flesh and blood are stepping on the edge of death. The real fear has made these fighters tremble helpless and discouraged countless times.There is no \"\"retreat\"\" in the dictionary of maritime rescue.When you hear the roar of the rotor the loud whistle and the flying of the motor it is a heroic song composed by them who are fearless of difficulties and dangers and sacrifice themselves for others.\"",
                classification: [
                    "disaster",
                    "action"
                ],
                rank: 6.2,
                release_time: "2020-12-18 (Chinese mainland",
                running_time: 134,
                is_released: 1,
                pic_src: "/poster/p2627025706.jpg",
                cert: "PG",
                sell_weeks: [14.4, 13.1, 15.4],
                totalTaking: 301,
                avgDayTaking: 14.3,
            },
            {
                id: 25,
                title: "Dear tenant",
                director: "Zheng Youjie",
                actor: "Mo Ziyi,Chen Shufang",
                blurb: "Lin Jianyi (Mo Ziyi) is a tenant living on the top floor but he not only takes care of the elderly and sick landlord Zhou Xiuyu (Chen Shufang) but also adopts her 9-year-old grandson Wang Youyu (Bai runyin)All this seems to be beyond the behavior motivation of ordinary tenants. After Zhou Xiuyu's death he was questioned. Many people suspected that he was in order to get the legacy and he could not argue because behind these actions there was an unrecognized feeling and also the way he missed someone who was the landlord's dead son",
                classification: [
                    "story"
                ],
                rank: 7.5,
                release_time: "2020-10-23 (Taiwan China) ",
                running_time: 106,
                is_released: 1,
                pic_src: "/poster/p2617989427.jpg",
                cert: "PG",
                sell_weeks: [13.4, 15.3, 16.9],
                totalTaking: 319,
                avgDayTaking: 15.2,
            },
            {
                id: 26,
                title: "Doraemon: accompany me 2",
                director: "Yamazaki Takashi",
                actor: " Huimei Ohara,jiashuyoumei",
                blurb: "\"\"\"Stand by me Doraemon 2\"\" officially announced that it will be released on August 7 next year.The story will be based on the original volume 4 \"\"memories of grandma\"\".\"",
                classification: [
                    "animation",
                    "plot"
                ],
                rank: 8.5,
                release_time: "2020-11-20 (Japan) ",
                running_time: 96,
                is_released: 1,
                pic_src: "/poster/p2622210998.jpg",
                cert: "PG",
                sell_weeks: [14.9, 14.6, 12.9],
                totalTaking: 296,
                avgDayTaking: 14.1,
            },
            {
                id: 27,
                title: "Crayon Xiaoxin: fierce battle!Graffiti Kingdom and four Warriors",
                director: "Jingji Shangyan",
                actor: "Yuko Kobayashi,Miocene",
                blurb: "\"Crayon Shin the 28th film will be released in Japan on April 24 2020. This work is also the 30th anniversary of Crayon Shin comics.The slogan is \"\"save the world!Crayons!Taking the graffiti kingdom as the stage this work tells the story of four brave men including Xiaoxin saving the world.\"",
                classification: [
                    "animation",
                    "family"
                ],
                rank: 8.7,
                release_time: "2020-09-11 (Japan) ",
                running_time: 103,
                is_released: 1,
                pic_src: "/poster/p2615830700.jpg",
                cert: "U",
                sell_weeks: [14.1, 16.3, 17.1],
                totalTaking: 333,
                avgDayTaking: 15.9,
            },
            {
                id: 28,
                title: "theatre",
                director: "Xing dingxun",
                actor: "Yamazaki,kuanichiro",
                blurb: "Yongtian started to set up a troupe with his friends from high school. He is also a screenwriter and director. However because his plays are too avant-garde many bad reviews have been received and the troupe is about to be dissolved.Until one day Yongtian on the road to wear the same shoes Shaxi pick up words.Shaxi and Yongtian who dream of becoming actors fall in love.Penniless Yongtian moved into Shaxi's home the two began to live together.Shaxi unconditionally supports Yongtian to pursue his dream and Yongtian gradually regains his love for drama.",
                classification: [
                    "plot",
                    "love"
                ],
                rank: 7.9,
                release_time: "2020-07-17 (Japan) ",
                running_time: 136,
                is_released: 1,
                pic_src: "/poster/p2610788779.jpg",
                cert: "12",
                sell_weeks: [16.4, 16.3, 16.6, 17.0, 15.0],
                totalTaking: 569,
                avgDayTaking: 16.3,
            },
            {
                id: 29,
                title: "bloody hell ",
                director: "Arist Gleason",
                actor: "Ben ottol,MEG Fraser,Caroline Craig",
                blurb: "A man with a mysterious past escapes the country escapes his own personal hell - just to a much worse place.",
                classification: [
                    "horror"
                ],
                rank: 7,
                release_time: "2020-09-09 (German Fantasy Film Festival) ",
                running_time: 94,
                is_released: 1,
                pic_src: "/poster/p2630884254.jpg",
                cert: "15",
                sell_weeks: [14.4, 14.7, 16.3, 16.3, 13.6],
                totalTaking: 527,
                avgDayTaking: 15.1,
            },
            {
                id: 30,
                title: "No place to depend on",
                director: "Zhao Ting",
                actor: "Francis mcdermond,David stretzen,Derek Janice",
                blurb: "\"Based on the book \"\"nomadland: Surviving America in the twenty first century\"\" written by Jessica Bruder this paper tells the story of a woman in her 60s who lost everything in the great depression. As a modern nomad living in a truck she began her journey across the western United States.\"",
                classification: [
                    "plot"
                ],
                rank: 8.3,
                release_time: "2020-09-11 (Venice Film Festival) ",
                running_time: 108,
                is_released: 1,
                pic_src: "/poster/p2630453887.jpg",
                cert: "PG",
                sell_weeks: [13.4, 15.3, 16.4],
                totalTaking: 316,
                avgDayTaking: 15.0,
            },
            {
                id: 31,
                title: "My life",
                director: "Mark Miles ",
                actor: "Jessica rod,Cen Yongkang,Mariel Scott",
                blurb: "Adapted from a real story the film was once on the Hollywood script blacklist directed by Mark Myers ([human capital]).The film tells about a couple of lovers Solomon and Jane who are planning their wedding. Solomon finds out that they have liver cancer. In order to fulfill their wish they decide to advance the wedding. With a kind donation they complete the wedding as they wish. Four months later Solomon dies.",
                classification: [
                    "plot",
                    "love"
                ],
                rank: 6.2,
                release_time: "2020-10-23 (UK) ",
                running_time: 93,
                is_released: 1,
                pic_src: "/poster/p2622809143.jpg",
                cert: "12",
                sell_weeks: [16.7, 14.3, 14.6, 16.1],
                totalTaking: 432,
                avgDayTaking: 15.4,
            },
            {
                id: 32,
                title: "The land abandoned by God",
                director: "AntonioCorreia De Campos ",
                actor: "Tom Holland,Robert Pattinson,bill scargaard",
                blurb: "It's a Midwestern Gothic film directed by Antonio campas about knockemstiff a remote Ohio State with the hero WillardRussell is desperate to save his dying wife and will not give in to sacrifice. His son (Holland) is growing up from a child abused at school to a man who knows when to fight. His roles include a couple of serial killers a missionary who tests people's faith and a corrupt local sheriff (Stan).Time from the end of World War II to the 1960s location from rural South Ohio to West Virginia.",
                classification: [
                    "plot",
                    "crime",
                    "thriller"
                ],
                rank: 7,
                release_time: "2020-09-16 (US network) ",
                running_time: 138,
                is_released: 1,
                pic_src: "/poster/p2619322729.jpg",
                cert: "15",
                sell_weeks: [14.1, 16.1, 12.9, 14.4],
                totalTaking: 403,
                avgDayTaking: 14.4,
            },
            {
                id: 33,
                title: "counterattack",
                director: "Zhao Wenzhuo",
                actor: "Zhao Wenzhuo,Jiang Yiyi,FireWire",
                blurb: "The film tells the story of Lu Ziming as a security expert who was invited to provide security work for an oil and gas plant project bidding activity but was deliberately framed by competitors betrayed by his colleagues and thrown by evil forces. In order to prove his innocence Lu Ziming searched for the truth of the incident staged a thrilling jungle chase and fought back by the Jedi.",
                classification: [
                    "action",
                    "suspense"
                ],
                rank: 4.9,
                release_time: "2021-02-15 (Chinese mainland",
                running_time: 137,
                is_released: 1,
                pic_src: "/poster/p2631923710.jpg",
                cert: "12",
                sell_weeks: [15.0, 16.9, 16.1],
                totalTaking: 336,
                avgDayTaking: 16.0,
            },
            {
                id: 34,
                title: "Disappearing Valentine's Day",
                director: "Chen YuXun",
                actor: "Liu Guanting,heijiajia",
                blurb: "Bus driver a Tai (Liu Guanting / decoration) is a slow action even the time of the watch the earthquake response are slower than others.Every day he would go to the post office and find the teller Yang Xiaoqi (Li Peiyu / ornament) to send a regular letter to whom he didn't know.Teller Yang Xiaoqi is the opposite of Artest. She is a super acute photographer but her love life has no progress. She is still a single mother in her late 30s.On the eve of Valentine's day Yang Xiaoqi is accosted by teacher Liu (Duncan / Chou Qun DA) a sunny man from Tiancai. Finally Xiaoqi and teacher Liu who are just beginning to fall in love with each other stir up a fire. Unexpectedly when they wake up there is no news from teacher Liu and Valentine's day has already passed?!Every day to send a letter of Artest never appeared... No memory of Yang Xiaoqi began a journey to find the truth of fantasy",
                classification: [
                    "comedy",
                    "love",
                    "fantasy"
                ],
                rank: 7.2,
                release_time: "2020-09-18 (Taiwan China) ",
                running_time: 119,
                is_released: 1,
                pic_src: "/poster/p2618456760.jpg",
                cert: "PG",
                sell_weeks: [17.0, 17.0, 14.0],
                totalTaking: 336,
                avgDayTaking: 16.0,
            },
            {
                id: 35,
                title: "Wonder woman 1984",
                director: "Patty Jenkins ",
                actor: "Gail gado,Chris pine,Christine Weg",
                blurb: "\"The background of the story is set in the colorful and tempting 1980s. Diana the wonder woman lives the same life as ordinary people in the natural history museum in Washington. However after stopping a seemingly ordinary robbery everything around her has changed.Under the temptation of powerful divine power two new enemies appear quietly: Leopard girl the top predator who \"\"loves and kills\"\" with wonder woman and Max Lord who controls the power that can change the world. It's inevitable that there will be a great battle.On the other hand the old love Steve suddenly \"\"came back from the dead\"\" and continued to lead Diana. However while being romantically moved Steve's return is also full of doubts.With the opening of a new era facing two powerful evil villains and the mysterious return of Steve how can wonder woman save the world again?\"",
                classification: [
                    "action",
                    "fantasy",
                    "adventure"
                ],
                rank: 6.3,
                release_time: "2020-12-18 (Chinese mainland",
                running_time: 151,
                is_released: 1,
                pic_src: "/poster/p2626959989.jpg",
                cert: "PG",
                sell_weeks: [14.1, 13.1, 15.3],
                totalTaking: 298,
                avgDayTaking: 14.2,
            },
            {
                id: 36,
                title: "Dawn is coming",
                director: "Naomi KAWASE ",
                actor: "Yongzuo Bomei,jingpuxin,Shitian beads",
                blurb: "\"The infertile Mr. and Mrs. Kurihara welcomed their lovely son Kurihara Chaodou through the adoption system. However their six-year happy life was immediately disrupted. A poor young woman suddenly visited and insisted that she was the child's biological mother. However she seemed to want more money compensation than the childNaomi Kawase a famous Japanese director focuses on women childbirth adoption and other social issues in her new work. She explores the identity of \"\"mother\"\" again with dramatic and impact strokes and provides real and complex emotional experience for the audience with a variety of narrative styles.\"",
                classification: [
                    "plot"
                ],
                rank: 7.1,
                release_time: "2020-09-16 (Toronto Film Festival) ",
                running_time: 139,
                is_released: 1,
                pic_src: "/poster/p2588296209.jpg",
                cert: "12",
                sell_weeks: [15.4, 15.3, 16.6],
                totalTaking: 331,
                avgDayTaking: 15.8,
            },
            {
                id: 37,
                title: "I'm the movie version of cell phone",
                director: "Fukuda shiichi",
                actor: "He Laixian,Kentaro ITO",
                blurb: "\"Taking the opportunity of school transfer Takashi Sanqiao decided to be \"\"arrogant\"\" in the new school and become a bad boy from then on.In order to get a sense of existence among his classmates he went to the hair salon to get a head of golden curly hair.Ito who was transferred to the same school with him had the same idea.On the first day of school ITO and Mitsuhashi discovered each other's secrets and formed allies.Sanqiao's creed is \"\"no matter how mean it is as long as it can win\"\". Therefore when fighting with others as long as it can play Yin it will never confront head-on but his real strength can not be underestimated.Ito is relatively serious in his life sometimes even slow so he is often used by Sanqiao and kept in the dark. In terms of fighting he has outstanding combat effectiveness and a belief in not giving up.Two people challenge the bad teenagers inside and outside the school together causing a series of hilarious events.\"",
                classification: [
                    "comedy"
                ],
                rank: 7.9,
                release_time: "2020-07-17 (Japan) ",
                running_time: 114,
                is_released: 1,
                pic_src: "/poster/p2595471914.jpg",
                cert: "PG",
                sell_weeks: [16.3, 14.7, 15.6, 15.6],
                totalTaking: 435,
                avgDayTaking: 15.5,
            },
            {
                id: 38,
                title: "Tom and Jerry",
                director: "Tim Story ",
                actor: "Chloe Moritz,Michael Penner",
                blurb: "\"\"\"Super kill girl\"\" Carol morritz as a young girl has just entered a luxury hotel when she meets with a headache - Jerry even wants to settle in the hotel which puts the century wedding that the hotel has recently undertaken in jeopardy.As a result Tom was employed by Kayla to become a hotel employee in order to drive away Jerry. The happy couple launched a hilarious comedy.\"",
                classification: [
                    "comic",
                    "animation",
                    "adventure"
                ],
                rank: 5.4,
                release_time: "2021-02-26 (US / Chinese mainland",
                running_time: 101,
                is_released: 1,
                pic_src: "/poster/p2632043260.jpg",
                cert: "U"
            },
            {
                id: 39,
                title: "To all the boys: love you forever",
                director: "Michael munnery",
                actor: "Lana Condor,Noah chendineo,Madeleine Arthur",
                blurb: "Laura who is about to graduate from high school is ready to enter the adult stage. Two life changing journeys make her realize that her relationship with family friends and Peter after graduation is not what she imagined.",
                classification: [
                    "comic",
                    "love"
                ],
                rank: 6.7,
                release_time: "2021-02-12 (USA) ",
                running_time: 115,
                is_released: 1,
                pic_src: "/poster/p2634122234.jpg",
                cert: "12",
                sell_weeks: [14.7, 16.1, 14.7],
                totalTaking: 319,
                avgDayTaking: 15.2,
            },
            {
                id: 40,
                title: "Love and monsters",
                director: "Michael Matthews",
                actor: "\"Dylan OBrien\",Jessica henwick,Michael rook",
                blurb: "The background of the story is set in a doomsday world in which most human beings have died. It is the mutated cold-blooded animals that dominate the power of life and death in this world.In order to survive the remaining human beings are forced to move into the underground fortress and live in fear all day.Joey (Dylan O'Brien Dylan O'Brien) is separated from his girlfriend Amy (Jessica henwick Jessica henwick) in the great disaster seven years ago. Now they live in two different bunkers and communicate by radio.One day Joey who misses Amy so much decides to step out of the safe area and return to the world on earth. He walks to Amy's camp alone. Along the way he meets countless dangers as well as mentor Clyde (Michael Rooker) and Mino (Ariana Greenblatt).Can the cowardly Joey live to see Amy?",
                classification: [
                    "adventure"
                ],
                rank: 7.2,
                release_time: "2020-10-16 (USA) ",
                running_time: 109,
                is_released: 1,
                pic_src: "/poster/p2622904695.jpg",
                cert: "15"
            },
            {
                id: 41,
                title: "Give you a little red flower",
                director: "Han Yan",
                actor: "A thousand seals,Liu haocun,Zhu Yuanyuan",
                blurb: "Two families two life paths.The film tells a warm and realistic story thinking and facing the ultimate problem that every ordinary person will face - imagining that death may come at any time. The only thing we have to do is to love and cherish.",
                classification: [
                    "plot"
                ],
                rank: 7.5,
                release_time: "2020-12-31 (Chinese mainland",
                running_time: 128,
                is_released: 1,
                pic_src: "/poster/p2618247457.jpg",
                cert: "PG",
                sell_weeks: [16.9, 14.4, 13.6, 13.4],
                totalTaking: 408,
                avgDayTaking: 14.6,
            },
            {
                id: 42,
                title: "take the crown",
                director: "Chen Kexin",
                actor: "Gong Li,Huang Bo,Wu Gang",
                blurb: "August 15 2008 Beijing Olympic Games women's volleyball match China vs the United States.Lang Ping (Gong Li) with gold rimmed glasses sits on the coach seat of the U.S. team with calm atmosphere and electric eyes while the coach of the Chinese team (Huang Bo) stands on the sideline absorbed and smiling.The coach of the Chinese team looked at Lang Ping with deep vision. The passing figures covered his vision. The ups and downs of the Chinese women's volleyball team for more than 30 years were slowly opened",
                classification: [
                    "plot"
                ],
                rank: 7.3,
                release_time: "2020-09-25 (Chinese mainland",
                running_time: 135,
                is_released: 1,
                pic_src: "/poster/p2620083313.jpg",
                cert: "U",
                sell_weeks: [14.6, 13.1, 16.0, 14.6, 15.1],
                totalTaking: 514,
                avgDayTaking: 14.7,
            },
            {
                id: 43,
                title: "Legend of looking for Dragon",
                director: "Don halcarlos Lopez Estrada Paul Briggs",
                actor: "Kelly Mary Chen,okafina,Jiama Chen",
                blurb: "Once upon a time in the land of dragon you which is full of fantastic colors human beings and dragons lived in harmony.But when an evil force came the Dragon sacrificed itself to save mankind.500 years later the same evil force returns. Only a lonely warrior Laya (Kelly Mary Chen) takes the heavy responsibility of tracking the last dragon in the legend to repair the broken land and unite the divided people.In her journey she will gradually learn that saving the world requires not only one-stop but also trust and teamwork.",
                classification: [
                    "animation",
                    "fantasy",
                    "adventure"
                ],
                rank: 7.3,
                release_time: "2021-03-05 (Chinese Mainland / US",
                running_time: 108,
                is_released: 1,
                pic_src: "/poster/p2633531206.jpg",
                cert: "U",
                sell_weeks: [15.6, 16.1, 13.6],
                totalTaking: 317,
                avgDayTaking: 15.1,
            },
            {
                id: 44,
                title: "Flora and squirrel",
                director: "Charles Martin Smith",
                actor: "Alison Hannigan,Ben Schwartz",
                blurb: "\"Disney is preparing to make a new film [flora and squirrel man] which will be launched on Disney's streaming media platform \"\"Disney DTC\"\" next year.Adapted from Kate dicamilo's novel of the same name (which won the Newbury prize for children's Literature) the film centers on the story of a little girl and a squirrel with super power.Director Lina Khan and screenwriter Brad Copland.Disney has previously said it will make four or five movies a year for Disney DTC which will be officially launched later next year.\"",
                classification: [
                    "comic",
                    "adventure"
                ],
                rank: 6,
                release_time: "2021-02-19 (US network) ",
                running_time: 110,
                is_released: 1,
                pic_src: "/poster/p2633807302.jpg",
                cert: "U",
                sell_weeks: [13.6, 16.7, 14.3, 15.1, 15.7],
                totalTaking: 528,
                avgDayTaking: 15.1,
            },
            {
                id: 45,
                title: "silent",
                director: "Ke zhennian",
                actor: "Chen fufei,Liu Ziquan,Liu Guanting",
                blurb: "\"Deaf teenager Zhang Cheng plans to transfer to qicong school.The world of the deaf is no quieter than that of the listening.When he found the game in the last row of the school bus the joy of integrating into the new life instantly became fear.Seeing her beloved girl Beibei bruised in the game Xiaoguang's arrogance can not be questioned and a group of students are innocent. Zhang Cheng wondered whether to uncover the cruel truth of the game or join the ranks of the game?When the boundaries between the perpetrators and the victims become more and more blurred the deep-rooted pain unspeakable resentment all kinds of confusion and uneasiness spread in the silent campus.The first feature film of cutting-edge director Ke zhennian boldly brings the real events to the screen while facing the cruelty directly he does not lose his gentle eyes.Sharp depiction of the complex and tangled emotions between the characters showing hoarse but still silent cruelty.Beibei's \"\"they're just playing\"\" understates it but it's terrifying painful and a real lament.\"",
                classification: [
                    "plot"
                ],
                rank: 7.7,
                release_time: "2020-10-15 (Taiwan China) ",
                running_time: 104,
                is_released: 1,
                pic_src: "/poster/p2619399682.jpg",
                cert: "15",
                sell_weeks: [13.7, 14.4, 16.1, 13.7, 12.9],
                totalTaking: 496,
                avgDayTaking: 14.2
            },
            {
                id: 46,
                title: "Judas and the black Messiah",
                director: "Saka King",
                actor: "Daniel callua,lekeith Steinfeld,Jesse premon",
                blurb: "\"The film is adapted from real people.The story focuses on the death of Hampton who was killed in 1969 and died in a raid organized by the Chicago police department and the FBI.The police fired 80 shots while the members of the \"\"Black Panther Party\"\" fired only one shot in total. This shot came from the muscle contraction of a member after being killed by the police.Hampton was sleeping with his pregnant fiancee when he was shot two times in the head at close range. He was drugged that night and didn't hear anything from the police. After his death his body was dragged into the alley. He was only 21 years old.After the trial his death was judged as \"\"just homicide\"\". Later in 1982 the amount of compensation reached an out of court settlement of the civil action with 1.85 million US dollars.\"",
                classification: [
                    "history",
                    "plot",
                    "biography"
                ],
                rank: 7.2,
                release_time: "2021-02-12 (US / US network) ",
                running_time: 126,
                is_released: 1,
                pic_src: "/poster/p2620539710.jpg",
                cert: "15",
                sell_weeks: [13.0, 14.1, 13.0],
                totalTaking: 281,
                avgDayTaking: 13.4,
            },
            {
                id: 47,
                title: "Start over after you get home",
                director: "Ryuta Inoue",
                actor: "Kogawa Xionghui,long Xingliang",
                blurb: "Kogawa Xionghui & long Xingliang cooperate for the first time!Co starring in the cure pure love BL manggai film \"\"start again after going home\"\" which will be released in Japan this fall!It tells the story of the pure love between Guangchen guzuka a proud and charming man who is tired of urban life and suffered from setbacks in life and the stable man Xiong jingdahe (long Xingliang) who lives in the countryside.",
                classification: [
                    "sex"
                ],
                rank: 6.6,
                release_time: "2020-09-04 (Japan) ",
                running_time: 99,
                is_released: 1,
                pic_src: "/poster/p2607822901.jpg",
                cert: "PG",
                sell_weeks: [17.1, 16.6, 13.1, 16.9],
                totalTaking: 446,
                avgDayTaking: 15.9,
            },
            {
                id: 48,
                title: "Detective Conan: Fei SE's alibi",
                director: "Yasuichiro Yamamoto ",
                actor: "Gao Shannan,Yamazaki and Kanai,xiaoshanliye",
                blurb: "The Akai family is a dangerous family with many real identity mysteries and everyone has a complex background.Hideki Akai an FBI agent who feigns his death in laiyeya is the center of the story. It reveals the personalities of Hideki Akai shiliangzhenchun Hideki Haneda and Mary as well as the relationship between them.The climax of the story is about Hideki Akai's gorgeous resurrection of \"\"Fei se\"\" series.In one incident Hideki Akai's old enemy an Shitou code named bourbon got \"\"clues\"\" from the FBI.After that an Shitou investigated the relationship between Akai and Chongya.After a series of high intelligence attack and defense the return of Hideki Akai has brought a shock to everyone.Behind the truth of this series of \"\"alibi plays\"\" there are Conan's figures the Akai family which is indispensable in the series of \"\"Detective Conan\"\". This collection will thoroughly dissect their action track so far and their relationship with Conan.\"",
                classification: [
                    "plot",
                    "action",
                    "animation"
                ],
                rank: 6.8,
                release_time: "2021-02-11 (Japan) ",
                running_time: 120,
                is_released: 1,
                pic_src: "/poster/p2631088441.jpg",
                cert: "PG",
                sell_weeks: [16.7, 14.1, 13.3, 13.6, 16.1],
                totalTaking: 517,
                avgDayTaking: 14.8,
            },
            {
                id: 49,
                title: "new order",
                director: "Michelle Frank",
                actor: "Diego bonetta",
                blurb: "Mexican director Michelle Frank confirmed at the Marrakesh film festival that his sixth film the dreams of a few will be released in April next year.Frank's last film [Apple's daughter] premiered last year at Cannes Film Festival \"\"a concern unit\"\" and won a jury award.Frank said that the new film will be a big production film the film style is different from his previous works will use all Mexican cast Mexico shooting.It is reported that the story of the new film will be set in an anti utopian world in the near future. The theme of the film involves the gap between the rich and the poor in Mexico City.",
                classification: [
                    "plot"
                ],
                rank: 6.9,
                release_time: "2020-09-10 (Venice Film Festival) ",
                running_time: 88,
                is_released: 1,
                pic_src: "/poster/p2621425697.jpg",
                cert: "15",
                sell_weeks: [14.4, 13.9, 16.3],
                totalTaking: 312,
                avgDayTaking: 14.9,
            },
            {
                id: 50,
                title: "Fall in love with you",
                director: "Metz Tara",
                actor: "Nadek kujimia,tiding · Mahayana",
                blurb: "Naive ina is a bank clerk. After her ex boyfriend's money collection and elopement with Xiao San she lives a hard life full of debt. After a chance meeting she meets a handsome but cunning liar by accident. However ina doesn't report to the police. Instead she decides to hire the liar and retaliates against her ex boyfriend which is a laughing trick of spy to spyHere we go!",
                classification: [
                    "comic",
                    "love"
                ],
                rank: 7,
                release_time: "2020-12-03 (Thailand) ",
                running_time: 127,
                is_released: 1,
                pic_src: "/poster/p2629407129.jpg",
                cert: "PG",
                sell_weeks: [16.3, 13.4, 13.1],
                totalTaking: 300,
                avgDayTaking: 14.3,
            },
            {
                id: 51,
                title: "Bob's Christmas present",
                director: "Charles Martin Smith",
                actor: "Luke tredewey,Anna Wilson Jones,Nina Wadia",
                blurb: "The film will focus on the life of James and aimao Bob review the last Christmas James and stray cat Bob spent in the street and how Bob helped him through the most difficult time and explore the true meaning of Christmas.",
                classification: [
                    "plot",
                    "comedy"
                ],
                rank: 7.5,
                release_time: "2020-11-06 (UK network) ",
                running_time: 92,
                is_released: 1,
                pic_src: "/poster/p2622755001.jpg",
                cert: "PG",
                sell_weeks: [15.7, 16.0, 12.9, 15.6, 17.0],
                totalTaking: 540,
                avgDayTaking: 15.4,
            },
            {
                id: 52,
                title: "white tiger",
                director: "Ramin Bahrani ",
                actor: "Adash gulaf,Raj Kumar",
                blurb: "Barron Harvey (adash gulaf) tells the story of his epic black humor life course from a poor villager to a successful contemporary Indian entrepreneur.Our young hero is resourceful and ambitious trying to become the driver of Ashok (Raji Kumar) and pink lady (piaka Chopra) who just came back from the United States.When the society trained Barron to be a servant he made great efforts to become the right helper of the rich master.But after a night of betrayal he realized that his masters would do anything to frame him for self-help.On the verge of losing everything Barron is determined to resist the manipulated life and the unequal system and rise up to become a new master.The film is adapted from the New York Times bestseller and the 2008 manbooker prize winning novel.",
                classification: [
                    "plot",
                    "crime"
                ],
                rank: 7.5,
                release_time: "2021-01-22 (US network) ",
                running_time: 125,
                is_released: 1,
                pic_src: "/poster/p2631140996.jpg",
                cert: "12",
                sell_weeks: [13.3, 13.1, 15.3, 14.7, 13.6],
                totalTaking: 490,
                avgDayTaking: 14.0,
            }
        ],
        months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        years: [
            {
                year: 2020,
                weeks: ['Jan w1', 'Jan w2', 'Jan w3', 'Jan w4',
                    'Feb w1', 'Feb w2', 'Feb w3', 'Feb w4',
                    'Mar w1', 'Mar w2', 'Mar w3', 'Mar w4', 'Mar w5',
                    'Apr w1', 'Apr w2', 'Apr w3', 'Apr w4',
                    'May w1', 'May w2', 'May w3', 'May w4',
                    'Jun w1', 'Jun w2', 'Jun w3', 'Jun w4', 'Jun w5',
                    'Jul w1', 'Jul w2', 'Jul w3', 'Jul w4',
                    'Aug w1', 'Aug w2', 'Aug w3', 'Aug w4',
                    'Sep w1', 'Sep w2', 'Sep w3', 'Sep w4', 'Sep w5',
                    'Oct w1', 'Oct w2', 'Oct w3', 'Oct w4',
                    'Nov w1', 'Nov w2', 'Nov w3', 'Nov w4',
                    'Dec w1', 'Dec w2', 'Dec w3', 'Dec w4', 'Dec w5'],
                weeks_data: [13076, 13694, 14669, 14424,
                    13592, 13101, 13222, 13261,
                    13362, 13029, 13076, 14397, 13023,
                    13210, 14348, 14996, 13273,
                    14560, 14253, 14804, 13459,
                    14204, 14297, 14038, 13943, 14266,
                    13895, 13502, 13680, 13421,
                    14618, 13138, 13664, 13228,
                    14478, 14286, 14737, 13980, 13572,
                    13960, 14155, 14723, 14479,
                    13945, 14145, 13838, 14059,
                    13124, 14127, 14918, 14113, 13676],
                month_data: [62575, 63001, 61547, 63378, 63189, 62275, 63572, 63819, 63140, 62751, 63637, 62239]

            },
        ]
    },
    mutations: {
        increment: state => state.count++,
        decrement: state => state.count--,
        setLoginState(state, n) {
            state.loggedIn = n;
        }
    }, actions: {
        login({ commit }) {
            commit('setLoginState', true);
        },
        logout({ commit }) {
            commit('setLoginState', false);
        }
    }
})